steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/harris-sandbox-293410/github.com/harris-agyeman/harris-pro:$SHORT_SHA', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/harris-sandbox-293410/github.com/harris-agyeman/harris-pro:$SHORT_SHA']
  
  
 
